name: BungeeReports
main: ru.frostdelta.bungeereports.TrackedLoader
version: 2.3.2
authors: [FrostDelta123]
description:
depend:
  - Inspector
commands:
  report:
    permission: bungeereports.player
  getreports:
    permission: bungeereports.admin
  br:
    permission: bungeereports.reload
  spectate:
    permission: bungeereports.spectate
  spectateoff:
    permission: bungeereports.spectate
  screen:
    permission: bungeereports.screen
  getscreens:
    permission: bungeereports.getscreens
