name: BungeeReports
main: ru.frostdelta.bungeereports.Loader
version: 4.4.3
authors: [FrostDelta123]
description:
commands:
  report:
    permission: bungeereports.player
  getreports:
    permission: bungeereports.admin
  br:
    permission: bungeereports.reload
  spectate:
    permission: bungeereports.spectate
  spectateoff:
    permission: bungeereports.spectate
  screen:
    permission: bungeereports.screen
  getscreens:
    permission: bungeereports.screen
  dump:
    permission: bungeereports.dump
  getdump:
    permission: bungeereports.dump
  getlogs:
    permission: bungeereports.admin