name: BungeeReports
main: ru.frostdelta.bungeereports.BungeeReports
version: 4.4.7
authors: [FrostDelta123]
description: BungeeReports bukkit plugin. Description here http://rubukkit.org/threads/mech-admin-bungeereports-v4-4-7-report-sistema-dlja-bungeecord-i-ne-tolko-1-7-10-1-13-2.158683/
website: http://rubukkit.org/threads/mech-admin-bungeereports-v4-4-7-report-sistema-dlja-bungeecord-i-ne-tolko-1-7-10-1-13-2.158683/
commands:
  report:
    permission: bungeereports.player
  getreports:
    permission: bungeereports.admin
  br:
    permission: bungeereports.reload
  spectate:
    permission: bungeereports.spectate
  spectateoff:
    permission: bungeereports.spectate
  screen:
    permission: bungeereports.screen
  getscreens:
    permission: bungeereports.screen
  dump:
    permission: bungeereports.dump
  getdump:
    permission: bungeereports.dump
  getlogs:
    permission: bungeereports.admin