#BungeeReports config v1.0

#Данные для подключения к базе данных.
url: jdbc:mysql://localhost:3306/test
username: test
password: test

#Список игнорируемых игроков
#На них нельзя отправить репорт
whitelist:
  - FrostDelta123
  - example

#Список причин, по которым можно отправить жалобу.
reasons:
  - test
  - чат
  - example

#Использовать bungee cord, если false, то bungee cord не используется и имя не задаётся. false по умолчанию.
bungee:
  enabled: false
  #имя сервера bungee cord, прописано в config. ALL для игроков со всех сервреов. ALL по умолчанию.
  servername: ALL

#Комментарии игроков к репортам, если true, то для отправки репорта игрок будет обязан оставить свой комментарий в чат,например скриншот.
#false по умолчанию.
comments: false

#Использование vault для наград
#Если true, то он загрузится
#ВАЖНО, при использовании НЕ кастомных наград vault должен быть true
#false по умолчанию
vault:
  enabled: false

#Использование наград за количество корректных репортов
#false по умолчанию
reward:
  enabled: false
  #Количество одобренных репортов, необходимых для выдачи наград
  reportsneed: 10
  #Награда
  amount: 1000

#Использование кастомных наград, если ваш плагин не поддерживает vault
#false по умолчанию
#ВАЖНО!!!
#Если включены оба вида наград - будет выдаваься через vault
customreward: 
  enabled: false
  #Количество одобренных репортов, необходимых для выдачи наград
  reportsneed: 10
  #Данные для базы данных, в которые нужно записывать награду
  table: test
  namecoloumn: name
  moneycoloumn: money
  #Использовать UUID вместо никнейма игрока в таблице кастомных наград
  #false по умолчанию
  uuid: false
  #Награда
  amount: 1000

#Лимит неодобренных репортов
#Если игрок подаёт слишком много репортов
#то при достижении лимита, он не сможет отправлять новые,
#пока они не будут проверены модератором
#true по умолчанию
limit:
  enabled: true
  limit: 10
