name: BungeeReports
main: ru.frostdelta.bungeereports.Loader
version: 1.0
authors: [FrostDelta123]
description:
commands:
  report:
    permission: bungeereports.player
  getreports:
    permission: bungeereports.admin
  br:
    permission: bungeereports.reload
