name: BungeeReports
main: ru.frostdelta.bungeereports.Loader
version: 2.1.5
authors: [FrostDelta123]
description:
commands:
  report:
    permission: bungeereports.player
  getreports:
    permission: bungeereports.admin
  br:
    permission: bungeereports.reload
  spectate:
    permission: bungeereports.spectate
  spectateoff:
    permission: bungeereports.spectate
